remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one



h1: esto es un h1
name: esto no es un h1 
mensaje: Ésta es una página realizada con jekyll
mensaje2: Esta es la principal



